# build_config.yaml - 项目构建配置

# 项目基本信息
project_name: PyBuilder
version: 1.0.0
company_name: ASLant
entry_file: main.py
icon_file: assets/app.ico

# 构建配置
build_tool: pyinstaller
output_dir: build
quiet_mode: true

# 打包选项
onefile: false
show_console: true
clean: true
noconfirm: true
debug: false
show_progressbar: false
contents_directory: lib
uac_admin: false
collect_submodules: textual
add_data: src\style;src\style assets\pyfiglet;pyfiglet docs;docs

# 排除的包
exclude_packages:
  - pytest
  - tkinter

# 安装包配置
installer_platform: windows
installer_app_name: PyBuilder
installer_version: 1.0.0
installer_publisher: ASLant
installer_exe_name: PyBuilder.exe
installer_source_dir: build
installer_output_dir: dist/installer
installer_icon: assets/app.ico
installer_appid: 3570A6C9-D68D-41D0-A6A0-4C3E3E4F8ECF
installer_privileges: lowest
installer_compression: lzma2/ultra64
installer_path_scope: user
installer_desktop_icon: true
installer_start_menu: true
installer_add_path: false
installer_run_after: true

