# build_config.yaml - 项目构建配置

# 项目基本信息
project_name: PyBuilder
version: 1.0.0
company_name: ASLant
entry_file: main.py
icon_file: assets/app.ico

# 构建配置
build_tool: pyinstaller
output_dir: build
quiet_mode: true

# 打包选项
onefile: false
show_console: true
clean: true
noconfirm: true
debug: false
show_progressbar: false
contents_directory: lib
uac_admin: false
collect_submodules: textual
collect_data: pyfiglet
add_data: src/style;src/style docs;docs

# 排除的包
exclude_packages:
  - pytest
  - tkinter

