[project]
name = "PyBuilder-Generate"
version = "1.0.0"
description = "跨平台 Python 编译脚本生成器 TUI 版本"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pyfiglet>=1.0.4",
    "textual>=6.6.0",
]

[project.scripts]
pybuilder-tui = "src.__main__:main"
